[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist/public"

[functions]
node_bundler = "esbuild"
external_node_modules = ["pg"]

[[redirects]]
from = "/api/recipes*"
to = "/.netlify/functions/recipes:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
